# Generated by Django 6.0.2 on 2026-02-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estado_alter_evento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
    ]
