# Generated by Django 4.2.23 on 2026-02-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_jugador_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('evento', 'Solo Evento'), ('torneo', 'Evento + Torneo')], default='evento', max_length=10),
        ),
        migrations.AlterField(
            model_name='boletagasto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='equipos_participantes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.IntegerField()),
                ('posicion', models.IntegerField()),
                ('equipo1_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('equipo2_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('ganador_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_matches', to='app.evento')),
            ],
            options={
                'ordering': ['ronda', 'posicion'],
                'unique_together': {('evento', 'ronda', 'posicion')},
            },
        ),
    ]
